
services:
  db:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    hostname: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: dieta
      POSTGRES_PASSWORD_FILE: /run/secrets/db-password
    volumes:
      - database-dieta:/var/lib/postgresql/data
    secrets:
      - db-password

  server:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    ports:
      - 3333:3333
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}

volumes:
  database-dieta:
secrets:
  db-password:
    file: db/password.txt
